version: '3.5'

services:
  servicios-mailcatcher:
    container_name: servicios-mailcatcher
    image: schickling/mailcatcher
    ports:
      - 1080:1080
      - 1025:1025

    networks:
      - servicios-network
  denuncias-phpunit-db:
    container_name: denuncias-phpunit-db
    build:
      context: ./docker/database
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - denuncias-phpunit-db-data:/var/lib/mysql
#      - /var/data/mysql:/var/lib/mysql
      - /etc/mysql:/etc/mysql
      - ./mysql-files:/var/lib/mysql-files
#      - denuncias-phpunit-db-data:/data/home/gerardo/mysql
    networks:
      - servicios-network
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]

networks:
  servicios-network:
    external: true
volumes:
  ###> doctrine/doctrine-bundle ###
  denuncias-phpunit-db-data:
###< doctrine/doctrine-bundle ###
